# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Rasterabsorber
                                 A QGIS plugin
 Add an new column for the vector layer through sampling values from a raster layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-05-31
        copyright            : (C) 2024 by Zijian Guo, HK PolyU
        email                : zijian1.guo@connect.polyu.hk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Rasterabsorber class from file Rasterabsorber.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .rasterabsorber import Rasterabsorber
    return Rasterabsorber(iface)
